name: Automated tests stand

on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: Choose target
        required: true
        default: stand
        type: choice
        options:
          - stand
          - preprod
          - prod
#on:
#  push

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install Chromium
        run: sudo apt-get install chromium-browser
      - name: Install dependecies
        run: pip install -r reguirements.txt
      - name: Install browsers
        run: playwright install
      - name: Run tests
        run: ENV=stand pytest
